[package]
name = "wgpustein"
version = "0.0.1"
edition = "2024"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
log = { version = "0.4.27", features = ["std", "max_level_trace", "release_max_level_info"] }
wasm-bindgen = "0.2.100"
